### ISSUE TITLE
Request to add new features.

### ISSUE THREAD

**Issue by Angelk90** [gsrathoreniks/FaceFilter#2]
@gsrathoreniks : It would be possible to add the following features:
1) The possibility of being able to change the camera, the back one with the front one, and so on.
2) The possibility that faceOverley, covers the whole screen of the device.

**Comment by gsrathoreniks** [comment]
@Angelk90 Thanks for opening a feature request. I'm working on it, soon you'll get better updates to see.

**Comment by Angelk90** [comment]
@gsrathoreniks: Are there any news?

**Comment by Angelk90** [comment]
@gsrathoreniks: Are there any news?
